### ISSUE TITLE
不能上传图片

### ISSUE THREAD

**Issue by yhliu-chn** [waketzheng/django-kindeditor#1]
两个问题，
一个是添加xadmin.site.register(Article, EditorAdmin)这句报错“TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases”
另一个是默认配置下无法上传图片吧？Not Found: /kindeditor/upload/，这个文件夹是建在哪里的？

**Comment by waketzheng** [comment]
抱歉啊，最近忙着做项目，都没登录github
1. 你的django版本？xadmin是第三方库还是自定义的类？
2. 你是linux系统还是windows？settings.MEDIA_ROOT是怎么设置的？

**Comment by yhliu-chn** [comment]
> 
> 
> 抱歉啊，最近忙着做项目，都没登录github
> 
>     1. 你的django版本？xadmin是第三方库还是自定义的类？
> 
>     2. 你是linux系统还是windows？settings.MEDIA_ROOT是怎么设置的？

没事呢，新年快乐~
1.django是2.1.4的版本，xadmin是采用的https://github.com/sshwsfc/xadmin 的xadmin2在pypi上下的，做了本地化注册，即安装后复制安装文件到自己的Project目录下注册，注册成功后再通过pip uninstall卸载。
2.我用的系统是Windows 10，settings.MEDIA_ROOT设置为：
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

因为也是边学边弄这个，所以很多设置都是按照教程上弄的，可能有些地方设置错了，所以不能正常使用。
谢谢。

**Comment by waketzheng** [comment]
你可以采用如下两种方案之一来修复这个问题

方案一： 卸载django-kindeditor然后安装最新版(>=0.1.1)，再把EditorAdmin替换为EditorAdminMixin
```bash
pip uninstall django-kindeditor && pip install django-kindeditor==0.1.1
```
```py
import xadmin
from kindeditor import EditorAdminMixin
from .models import Article

xadmin.site.register(Article, EditorAdminMixin)
```

方案二：不改django-kindeditor版本，自己实现一个EditorAdminMixin
```py
import xadmin
from kindeditor import EditorAdmin
from .models import Article

class EditorAdminMixin:
    class Media(EditorAdmin.Media):
        pass

xadmin.site.register(Article, EditorAdminMixin)
```
